import Head from "next/head"

export default function Greeting() {
  return(
    <>
      <Head>
          <title>Greeting</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <div className="mt-10 px-5">
            <h3 className="text-3xl font-bold text-center">SELAMAT ULANG TAHUN LENDYYYY</h3>
            <div className="px-4 md:px-36 lg:px-48">
              <div className="mt-10 text-lg text-start">
                Wih udah 19 tahun aja, keren banget loh udah bisa hidup selama itu. Btw... kontrak sama malaikat izroil berapa tahun? hehehehe. Semester 2 juga udah mau selesai gimana mental aman? pasti aman lah ya wong masih semester 2, plan semester 3 nya gimana masih mau ikut volunteer PDD ? melelahkan nggak sih ikut vonlunteer mending kayak aku kegiatan nya cuma kuliah pulang tok.
              </div>
              <div className="mt-10 text-lg text-start">
                Wishlist mu di umur segini apa? jangan jawab pengen dijemput izroil ya! kasian cantik cantik mati muda. Kataku sih jangan mati dulu sebelum ke rinjani bareng aku hehehe. Ehhh.. tapi mati duluan gapapa seh 
              </div>
              <div className="mt-10 text-lg text-start">
                Kalau ini beneran wes, mau doain. Semoga panjang umur, sehat selalu dilancarkan rejekinya, dimudahkan segala urusannya, dipertemukan jodohnya, dimatangkan pendiriannya, terus opo maneh yooo. Pokok yang terbaik wes buat kamu.
              </div>
              <div className="mt-10 text-lg text-start">
                Beli nangka ke wonogiri wes gaiso berkata kata soale udah jam empat pagi, hehehe ngantuk euy...
              </div>
              <div className="mt-10 text-lg text-start">
                Maaf lek greeting e plain banget aku gaiso designnnnnnnn
              </div>
              <div className="mt-10 text-lg text-center pb-8">
                @laravel2004
              </div>
            </div>
          </div>
        </main>
    </>
  )
}